server:
  port: 8080

logging:
  pattern:
    level:

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: serviceA-group
    template:
      default-topic: request-topic

kafka:
  topic:
    name: request-topic
    response: response-topic
  consumer:
    group-id: serviceA-group
